@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "org.example.Polynom#Polynom()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": true,
    "showMethodParametersNames": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "TypesAndMethods", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "org.example.Polynom",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Polynom1526836320[
	label="(C)Polynom"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

subgraph cluster_1413243858 { 
   	label=Polynom
	labeljust=l
	fillcolor=white
	style=filled
   
   Polynom1526836320XXXPolynom0[
	label="+ Polynom()"
	style=filled
	fillcolor=white
	tooltip="Polynom

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_1873443469 { 
   	label=GUI
	labeljust=l
	fillcolor=white
	style=filled
   
   GUI1526836320XXXactionPerformed1067311644[
	label="+ actionPerformed(e: ActionEvent)"
	style=filled
	fillcolor=white
	tooltip="GUI

null"
	fontcolor=darkgreen
];

GUI1526836320XXXsetMapFromRegex714116445[
	label="+ setMapFromRegex(tf: JTextField): Polynom"
	style=filled
	fillcolor=white
	tooltip="GUI

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_532501926 { 
   	label=Operations
	labeljust=l
	fillcolor=white
	style=filled
   
   Operations1526836320XXXaddPoly493550604[
	label="+ addPoly(p1: Polynom, p2: Polynom): Polynom"
	style=filled
	fillcolor=white
	tooltip="Operations

null"
	fontcolor=darkgreen
];

Operations1526836320XXXderivativePoly1267140448[
	label="+ derivativePoly(p: Polynom): Polynom"
	style=filled
	fillcolor=white
	tooltip="Operations

null"
	fontcolor=darkgreen
];

Operations1526836320XXXdividePoly493550604[
	label="+ dividePoly(p: Polynom, q: Polynom): String"
	style=filled
	fillcolor=white
	tooltip="Operations

null"
	fontcolor=darkgreen
];

Operations1526836320XXXintegratePoly1267140448[
	label="+ integratePoly(p: Polynom): Polynom"
	style=filled
	fillcolor=white
	tooltip="Operations

null"
	fontcolor=darkgreen
];

Operations1526836320XXXmultiplyPoly493550604[
	label="+ multiplyPoly(p1: Polynom, p2: Polynom): Polynom"
	style=filled
	fillcolor=white
	tooltip="Operations

null"
	fontcolor=darkgreen
];

Operations1526836320XXXsubstractPoly493550604[
	label="+ substractPoly(p1: Polynom, p2: Polynom): Polynom"
	style=filled
	fillcolor=white
	tooltip="Operations

null"
	fontcolor=darkgreen
];
} 
} 

'edges    
GUI1526836320XXXactionPerformed1067311644 -> GUI1526836320XXXsetMapFromRegex714116445;
GUI1526836320XXXactionPerformed1067311644 -> Operations1526836320XXXaddPoly493550604;
GUI1526836320XXXactionPerformed1067311644 -> Operations1526836320XXXderivativePoly1267140448;
GUI1526836320XXXactionPerformed1067311644 -> Operations1526836320XXXdividePoly493550604;
GUI1526836320XXXactionPerformed1067311644 -> Operations1526836320XXXintegratePoly1267140448;
GUI1526836320XXXactionPerformed1067311644 -> Operations1526836320XXXmultiplyPoly493550604;
GUI1526836320XXXactionPerformed1067311644 -> Operations1526836320XXXsubstractPoly493550604;
GUI1526836320XXXactionPerformed1067311644 -> Polynom1526836320XXXPolynom0;
GUI1526836320XXXsetMapFromRegex714116445 -> Polynom1526836320XXXPolynom0;
GUI1526836320XXXsetMapFromRegex714116445 -> Polynom1526836320[label=return, style=dashed];
Operations1526836320XXXaddPoly493550604 -> Polynom1526836320XXXPolynom0;
Operations1526836320XXXaddPoly493550604 -> Polynom1526836320[label=p1, style=dashed];
Operations1526836320XXXaddPoly493550604 -> Polynom1526836320[label=p2, style=dashed];
Operations1526836320XXXaddPoly493550604 -> Polynom1526836320[label=return, style=dashed];
Operations1526836320XXXderivativePoly1267140448 -> Polynom1526836320XXXPolynom0;
Operations1526836320XXXderivativePoly1267140448 -> Polynom1526836320[label=p, style=dashed];
Operations1526836320XXXderivativePoly1267140448 -> Polynom1526836320[label=return, style=dashed];
Operations1526836320XXXdividePoly493550604 -> Operations1526836320XXXmultiplyPoly493550604;
Operations1526836320XXXdividePoly493550604 -> Operations1526836320XXXsubstractPoly493550604;
Operations1526836320XXXdividePoly493550604 -> Polynom1526836320XXXPolynom0;
Operations1526836320XXXdividePoly493550604 -> Polynom1526836320[label=p, style=dashed];
Operations1526836320XXXdividePoly493550604 -> Polynom1526836320[label=q, style=dashed];
Operations1526836320XXXintegratePoly1267140448 -> Polynom1526836320XXXPolynom0;
Operations1526836320XXXintegratePoly1267140448 -> Polynom1526836320[label=p, style=dashed];
Operations1526836320XXXintegratePoly1267140448 -> Polynom1526836320[label=return, style=dashed];
Operations1526836320XXXmultiplyPoly493550604 -> Polynom1526836320XXXPolynom0;
Operations1526836320XXXmultiplyPoly493550604 -> Polynom1526836320[label=p1, style=dashed];
Operations1526836320XXXmultiplyPoly493550604 -> Polynom1526836320[label=p2, style=dashed];
Operations1526836320XXXmultiplyPoly493550604 -> Polynom1526836320[label=return, style=dashed];
Operations1526836320XXXsubstractPoly493550604 -> Polynom1526836320XXXPolynom0;
Operations1526836320XXXsubstractPoly493550604 -> Polynom1526836320[label=p1, style=dashed];
Operations1526836320XXXsubstractPoly493550604 -> Polynom1526836320[label=p2, style=dashed];
Operations1526836320XXXsubstractPoly493550604 -> Polynom1526836320[label=return, style=dashed];
    
}
@enduml